version: '3.1'

services:

  nginx :

    image : nginx
    depends_on : [ designer , airflow , notebook ]
    volumes:
      - ./DONOTREMOVE/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./DONOTREMOVE/cert:/cert
    ports :
      - 443:443
    command : [ "nginx" , "-g" , "daemon off;" ]

  designer :
    image : kinisi/designer
    build :
      context : .
    user : ${USER}

    environment :
      - BASIC_USERNAME=${USERNAME}
      - BASIC_PASSWORD=${USERPASS}
      - SERVER_NAME=${SERVERNAME}
      - VALIDATE=${VALIDATE}
      - GENALL=${GENALL}
      - DB=/home/kinisi/system/kinisi.db
    volumes:
      - ./system:/home/kinisi/system
      - ./dags:/home/kinisi/dags
      - ./logs:/home/kinisi/logs

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata

  airflow :
    image: kinisi/airflow:${AIRFLOW_VERSION}
    build :
      context : .
    user : ${USER}
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Local
      - AIRFLOW__WEBSERVER__BASE_URL=http://x/airflow
    command: webserver
    volumes:
      - ./dags:/home/airflow/dags
      - ./user:/home/airflow/udm
      - ./workarea:/workarea
      - ./system:/home/kinisi/system
      - ./logs:/home/airflow/klogs
      - ./certs:/certs

  notebook :
    image: jupyter/base-notebook
    build :
      context : .
    working_dir : /home/kinisi
    user : ${USER}
    volumes:
      - ./dags:/home/kinisi/dags
      - ./user:/home/kinisi/udm
      - ./workarea:/home/kinisi/workarea
      - ./logs:/home/kinisi/logs
      - ./certs:/home/kinisi/certs
    command : [ "jupyter", "lab", "--no-browser","--NotebookApp.token=''","--NotebookApp.password=''","--NotebookApp.base_url=/pyed"]

networks:
  default:
    external:
      name: kinisi-net

